### ISSUE TITLE
Dupe bug with cake and more

### ISSUE THREAD

**Issue by MrNilus** [Direwolf20-MC/LogisticsLasers#10]
It only uses 1 milk bucket but gives 3 empty back. 
Same for cakes. Used 1/6 when Crafting the Rat Upgrade: Chef.

**Comment by angelnc1989** [comment]
I believe this is the same as #8 .
It happens when you're crafting something and ingredients of one type are split up in more than 1 stack.

**Comment by Direwolf20-MC** [comment]
Thank you :)
