### ISSUE TITLE
Lasers not showing with wrench in the hand

### ISSUE THREAD

**Issue by Taccio33** [Direwolf20-MC/LogisticsLasers#11]
So the lasers don't seem to work, the power usage (only indication that I can take) seems to decrease and increase between 7 and 12 FE/t, suggesting that it actually connect some parts of the system, but not all of if. e.g.: even if I link a module to a node, the same node to a crafting station and a controller within a very short range it still doesn't show the items in the crafting station. 
Forge version: 35.1.3
PS: also a localization issue, the name of the mod in the creative item interface shows up broken

**Comment by Direwolf20-MC** [comment]
I can't replicate this issue, its probably due to another mod conflicting with ours somehow. Do you have any other mods installed? Can you remove them and see if you still have the issue?

Closing for now, unless we can confirm a bug on this side.

**Comment by Taccio33** [comment]
Starting to test this out, actually seems to be a mod conflic as oyu suggested, since playing with a very small amount of mods seems to work. Hope to find it sooner than later!
