### ISSUE TITLE
Item stuck

### ISSUE THREAD

**Issue by Zenthae** [Direwolf20-MC/LogisticsLasers#26]
i can't find a way to get items out of the laser controller, they got here because i requested items when there was not enough space available in the crafting station inventory

![image](https://user-images.githubusercontent.com/32647899/120448188-9ace1680-c38b-11eb-8d0b-f606f3283025.png)

**Comment by Trinsec** [comment]
Facing the same issue here. Why does that thing even have an inventory of sorts?

Also, when there's items stuck in the controller, the power usage is out of the roof. When breaking down the controller and placing it back and reconnecting it (and also losing those stuck items in the process) the power usage was back to normal.

**Comment by MichaelHillcox** [comment]
You're not meant to be using the laser controller? You need the crafting one right?

**Comment by Trinsec** [comment]
That's correct, but as mentioned by the OP, stuff gets stuck in the controller because the crafting station got full and you kept requesting things. So things get stuck in the laser controller... how to get it out? No clue. Shift-clicking your own inventory to the laser controller hangs the game (see the other issue #23). Breaking the controller voids those items. Fun times.

**Comment by MichaelHillcox** [comment]
Hmm, intresting... Noted

**Comment by Direwolf20-MC** [comment]
Give the items somewhere to go :) like a chest. They’ll auto empty from the controller. It’s overflow protection.

**Comment by Trinsec** [comment]
But how? I've already emptied the crafting station so they could go there (with a delay, that'd be fine)... but how do you trigger that? They're just stuck in the controller.

**Comment by Direwolf20-MC** [comment]
Connect up a chest with a module that accepts any item.

**Comment by Trinsec** [comment]
Ahhhh! Thanks, that worked!

I'd suggest to have some hint of it somewhere in the laser controller if people see items stuck in there.
