### ISSUE TITLE
Bug: The lasers that connect the nodes get stuck when you pick up a node with Carry On

### ISSUE THREAD

**Issue by michaelingrum** [Direwolf20-MC/LogisticsLasers#30]
Version 1.0.1 of laserIO

I notice today that if you pick up a laser node with Carry On the lasers that render between nodes stick around.
Might be a bug, might be an art feature! 😁  

![2022-05-27_20 23 41](https://user-images.githubusercontent.com/36677776/170808089-0e9b7e73-720b-4777-8398-6d29398e6a95.png)

**Comment by Direwolf20-MC** [comment]
Wrong mod :). But I’ll investigate it.
