### ISSUE TITLE
Inventory nodes will not extract from or insert into drawer controllers

### ISSUE THREAD

**Issue by ProfessorBiddle** [Direwolf20-MC/LogisticsLasers#5]

**Comment by MichaelHillcox** [comment]
This is likely due to the odd way that draw controllers work, it'll likely need direct mod intergration, definitely something to look into for us.

**Comment by hvdklauw** [comment]
Worked for me, chest with extractor and drawer controller with polymorph module configured for the item with a locked drawer that holds the item, it went in just fine for me.

Logistics lasers 1.0.7
Storage Drawerrs 1.16.3-8.2.1
Forge: 34.1.42
Minecraft; 1.16.3

**Comment by hvdklauw** [comment]
Basic inserter module also works

Just remember to configure it to an empty blacklist

**Comment by Direwolf20-MC** [comment]
Tested in dev environment, seems to work fine. Unfortunately the drawers allow oversending (items send to the drawer when its full already) but I believe thats a bug on their side.
