### ISSUE TITLE
The red overlay in the crafting table should also signal if there aren't items in the network

### ISSUE THREAD

**Issue by gamma-delta** [Direwolf20-MC/LogisticsLasers#7]
Maybe the overlay can be red if the item is missing from the whole network, and yellow if it's in the table but not in the network? It seems like that would be more useful, because it's much easier to see at a glance if you're missing something in the internal inventory than missing something in the network.

Once you add autocrafting maybe the overlay can be blue or something if the item doesn't exist but is craftable?

**Comment by Mali321** [comment]
I think you mean red if it's missing from the whole network, and yellow if it's just missing from the crafting inventory? So red highlighted items are ones that need adding to the network (or autocrafting) whilst yellow ones just need to be requested? I like the idea of another colour for autocraftable as well.

**Comment by gamma-delta** [comment]
@Mali321 Yes that's what I meant. To clarify:

- Red = Does not exist anywhere
- Yellow = Exists in the network but not in the table
- Blue = Does not exist anywhere but is autocraftable
- No color = Exists in the table.

**Comment by Direwolf20-MC** [comment]
Implemented yellow overlay - will add blue once autocrafting is in :)

https://github.com/Direwolf20-MC/LogisticsLasers/commit/4d2bd64f3cc03a401b7cadc6d876cbac5ed54403
